// Typelizer digest 6a16a9bc893252ee0f18089602675fc2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as home } from './HomeController'
export { default as orders } from './OrdersController'

import _orders from './OrdersController'
import _home from './HomeController'

export const order = _orders.update
export const root = _home.index
