// Typelizer digest ce93ed7c2e7bbe78e9431b4839b97894
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type HomeIndex = {
  orders: Array<Order>;
}

export type { HomeIndex };
