// Typelizer digest 1134d0c7a581583b6269c1d65a1242d1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {StatusAction} from '@/types'

type Order = {
  id: number;
  customer_name: string;
  status: string;
  total_cents: number;
  address: string;
  actions: Array<StatusAction>;
}

export type { Order };
