// Typelizer digest cc588eca154ad13c2214c499261a5ddb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Order = {
  id: number;
  customer_name: string;
  status: string;
  total_cents: number;
  address: string;
}

export type { Order };
