// Typelizer digest ce4af4f9a8fb104798c6db37e75c6520
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type StatusAction = {
  event: string;
  label: string;
  variant: string;
  to: string;
}

export type { StatusAction };
